/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_myACC_DriverButtonActivationTest_driverActionAndActive_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.1 (Backend: Code Generator V7.4.0)
*
* @date    03.03.2020 14:35:14
*
* @brief   "components_myACC_DriverButtonActivationTest_driverActionAndActive>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_myACC_DriverButtonActivationTest_driverActionAndActive_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "myWorkUnitTests_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_myACC_DriverButtonActivationTest_driverActionAndActive'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_myACC_DriverButtonActivationTest_driverActionAndActive_Automatic_driverActionAndActive'
 * ----------------------------------------------------------------------------
 * model name:...................................'driverActionAndActive'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_myACC_DriverButtonActivationTest_driverActionAndActive_Automatic_driverActionAndActive (void)
{
   /* user defined local variables */
   uint8 accActiveOut;
   uint8 buttonIn;
   uint8 driverAction;

   driverAction = true;
   buttonIn = true;
   accActiveOut = myWork_accButtonLogic_Automatic_calc(driverAction, buttonIn);
   ASSERT_FALSE(accActiveOut);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_myACC_DriverButtonActivationTest_driverActionAndActive_Automatic_driverActionAndActive'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



