/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_myACC_DeactivateOnBrakeTests_inactiveACCAndBrake_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.1 (Backend: Code Generator V7.4.0)
*
* @date    03.03.2020 14:35:14
*
* @brief   "components_myACC_DeactivateOnBrakeTests_inactiveACCAndBrake>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_myACC_DeactivateOnBrakeTests_inactiveACCAndBrake_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "myWorkUnitTests_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_myACC_DeactivateOnBrakeTests_inactiveACCAndBrake'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_myACC_DeactivateOnBrakeTests_inactiveACCAndBrake_Automatic_inactiveACCAndBrake'
 * ----------------------------------------------------------------------------
 * model name:...................................'inactiveACCAndBrake'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_myACC_DeactivateOnBrakeTests_inactiveACCAndBrake_Automatic_inactiveACCAndBrake (void)
{
   /* user defined local variables */
   uint8 accActiveIn;
   uint8 accActiveOut;
   float32 brake;

   brake = 0.0F;
   accActiveIn = false;
   accActiveOut = myWork_deactivateOnBrake_Automatic_calc(accActiveIn, brake);
   ASSERT_FALSE(accActiveOut);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_myACC_DeactivateOnBrakeTests_inactiveACCAndBrake_Automatic_inactiveACCAndBrake'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



