#ifndef _ASD_COMPONENTS_MYACC_DEACTIVATEONBRAKETESTS_INACTIVEACCANDBRAKE_AUTOMATIC_H_
#define _ASD_COMPONENTS_MYACC_DEACTIVATEONBRAKETESTS_INACTIVEACCANDBRAKE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_myACC_DeactivateOnBrakeTests_inactiveACCAndBrake_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.1 (Backend: Code Generator V7.4.0)
*
* @date    03.03.2020 14:35:14
*
* @brief   "components_myACC_DeactivateOnBrakeTests_inactiveACCAndBrake>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "myWork_deactivateOnBrake_Automatic.h"


/* component structure for module COMPONENTS_MYACC_DEACTIVATEONBRAKETESTS_INACTIVEACCANDBRAKE_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: components_myACC_DeactivateOnBrakeTests_inactiveACCAndBrake_Automatic */
#define _components_myACC_DeactivateOnBrakeTests_inactiveACCAndBrake_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_myACC_DeactivateOnBrakeTests_inactiveACCAndBrake_Automatic
 ******************************************************************************/
extern void components_myACC_DeactivateOnBrakeTests_inactiveACCAndBrake_Automatic_inactiveACCAndBrake (void);



#endif /* _ASD_COMPONENTS_MYACC_DEACTIVATEONBRAKETESTS_INACTIVEACCANDBRAKE_AUTOMATIC_H_ */
