#ifndef ESDL_MESSAGECOPY_H
#define ESDL_MESSAGECOPY_H

/**
  * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  * 
  * @file    esdl_messageCopy.h
  * 
  * @author  Generated by ASCET-DEVELOPER V7.4.1
  * 
  * @date    3/3/2020 2:35:16 PM
  * 
  * @brief   Header file for message copy logic
  **/



#endif /* ESDL_MESSAGECOPY_H */
