#ifndef GLOBALH_H
#define GLOBALH_H
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 * 
 * @file    globalH.h
 * 
 * @author  Generated by ASCET-DEVELOPER V7.4.1
 * 
 * @date    03.03.2020 14:03:15
 * 
 * @brief   this global header file supports pre-compiled header feature
 * 
 **/
#include "esdl.h"
#endif /* GLOBALH_H */
