#ifndef _ASD_MYWORKUNITTESTS_AUTOMATIC_H_
#define _ASD_MYWORKUNITTESTS_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    myWorkUnitTests_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.1 (Backend: Code Generator V7.4.0)
*
* @date    03.03.2020 14:35:14
*
* @brief   "myWorkUnitTests>>Automatic (project code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "assertLib_Assert_Impl.h"
#include "components_myACC_DeactivateOnBrakeTests_Automatic.h"
#include "components_myACC_DeactivateOnBrakeTests_activeACCAndBrake_Automatic.h"
#include "components_myACC_DeactivateOnBrakeTests_activeACCAndNoBrake_Automatic.h"
#include "components_myACC_DeactivateOnBrakeTests_inactiveACCAndBrake_Automatic.h"
#include "components_myACC_DeactivateOnBrakeTests_inactiveACCAndNoBrake_Automatic.h"
#include "components_myACC_DriverButtonActivationTest_Automatic.h"
#include "components_myACC_DriverButtonActivationTest_driverActionAndActive_Automatic.h"
#include "components_myACC_DriverButtonActivationTest_driverActionAndNoButton_Automatic.h"
#include "components_myACC_DriverButtonActivationTest_noDriverActionAndButton_Automatic.h"
#include "components_myACC_DriverButtonActivationTest_noDriverActionAndNoButton_Automatic.h"


/* component structure for project MYWORKUNITTESTS_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ..................myWorkUnitTests_Automatic */
#define _myWorkUnitTests_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project myWorkUnitTests_Automatic
 ******************************************************************************/



#endif /* _ASD_MYWORKUNITTESTS_AUTOMATIC_H_ */
