#ifndef _ASD_MYWORK_ACCBUTTONLOGIC_AUTOMATIC_H_
#define _ASD_MYWORK_ACCBUTTONLOGIC_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    myWork_accButtonLogic_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.1 (Backend: Code Generator V7.4.0)
*
* @date    03.03.2020 14:35:14
*
* @brief   "myWork_accButtonLogic>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for class MYWORK_ACCBUTTONLOGIC_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ............myWork_accButtonLogic_Automatic */
#define _myWork_accButtonLogic_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class myWork_accButtonLogic_Automatic
 ******************************************************************************/
extern uint8 myWork_accButtonLogic_Automatic_calc (
   /* IN    */ const uint8 driverAction,
   /* IN    */ const uint8 accButtonAction
   );



#endif /* _ASD_MYWORK_ACCBUTTONLOGIC_AUTOMATIC_H_ */
